const currencies = [
	{ code: 'BTC', label: 'BTC', symbol: '₿', suggested: true },
	{ code: 'EU', label: 'EUR', symbol: '€', suggested: true },
	{ code: 'US', label: 'USD', symbol: '$', suggested: true },
	{ code: 'GB', label: 'GBP', symbol: '£', suggested: true },
	{ code: 'CA', label: 'CAD', symbol: 'kan$', suggested: true },
	{ code: 'CN', label: 'CNY', symbol: 'RMB¥', suggested: true },
	{ code: 'AU', label: 'AUD', symbol: 'AU$', suggested: true },
	{ code: 'JP', label: 'JPY', symbol: '¥', suggested: true },
	{ code: 'CH', label: 'CHF', symbol: 'Fr.' },
	{ code: 'DK', label: 'DKK', symbol: 'dkr.' },
	{ code: 'HK', label: 'HKD', symbol: 'HK$' },
	{ code: 'HR', label: 'HRK', symbol: 'kn' },
	{ code: 'HU', label: 'HUF', symbol: 'Ft' },
	{ code: 'ID', label: 'IDR', symbol: 'Rp.' },
	{ code: 'IL', label: 'ILS', symbol: 'NIS' },
	{ code: 'IS', label: 'ISK', symbol: 'ikr' },
	{ code: 'MM', label: 'MMK', symbol: 'K' },
	{ code: 'MO', label: 'MOP', symbol: 'Pat.' },
	{ code: 'MV', label: 'MVR', symbol: 'ރ' },
	{ code: 'MX', label: 'MXN', symbol: 'Mex$' },
	{ code: 'MY', label: 'MYR', symbol: 'M$' },
	{ code: 'NA', label: 'NAD', symbol: 'N$' },
	{ code: 'NO', label: 'NOK', symbol: 'nkr' },
	{ code: 'NZ', label: 'NZD', symbol: 'NZ$' },
	{ code: 'PA', label: 'PAB', symbol: '฿' },
	{ code: 'PE', label: 'PEN', symbol: 'S/' },
	{ code: 'PH', label: 'PHP', symbol: '₱' },
	{ code: 'PL', label: 'PLN', symbol: 'Zł' },
	{ code: 'PY', label: 'PYG', symbol: '₲' },
	{ code: 'QA', label: 'QAR', symbol: 'QR' },
	{ code: 'RU', label: 'RUB', symbol: '₽' },
	{ code: 'SA', label: 'SAR', symbol: 'SR' },
	{ code: 'SG', label: 'SGD', symbol: 'S$' },
	{ code: 'TH', label: 'THB', symbol: '฿' },
	{ code: 'TR', label: 'TRY', symbol: '₺' },
	{ code: 'TW', label: 'TWD', symbol: 'NT$' },
	{ code: 'TZ', label: 'TZS', symbol: 'TSh' },
	{ code: 'UY', label: 'UYU', symbol: '$U' },
	{ code: 'VN', label: 'VND', symbol: '₫' },
	{ code: 'ZA', label: 'ZAR', symbol: 'R' }
];

export default currencies;
